### ISSUE TITLE
Add Koa Support

### ISSUE THREAD

**Issue by darthtrevino** [atsid/generator-ats-node-webapp#110]
Since generators are supported by default in NodeJS 4.x+, it would be interesting to have a Koa server option.

**Comment by bmathews** [comment]
Koa's in the middle of switching to promises and async/await at the moment:

https://github.com/koajs/koa#example

**Comment by darthtrevino** [comment]
That looks more like they're supporting several styles of middleware flow. Is there any documentation on why they would deprecate generators?

**Comment by bmathews** [comment]
They're switching from generators to promises, so if you want to use generators it's up to you to wrap them with something like `co-wrap` to convert a generator to a promise.

> If you want to convert a co-generator-function into a regular function that returns a promise, you now use `co.wrap(fn*)`

**Comment by darthtrevino** [comment]
I see; that's kind of a bizarre change

**Comment by bmathews** [comment]
Using generators for async control flow has always been a stopgap until async/await was available. In V8, the technology for generators contains the building blocks for async/await so that's why that (unfortunately) shipped first. Since async/await works on promises, koa is now just a promise-based framework instead of generator-based. 

It is unfortunate though that we now need babel or co.wrap to get the benefits of koa, at least until async/await ships in node. The good news is that promises are way faster than the current implementation of native generators.

**Comment by darthtrevino** [comment]
Interesting - I didn't know that promises were faster than generators. Generators read well compared to promises.

Regardless, it shouldn't be horrible to add a `server-koa` generator and rename the `server-full` generator to `server-express`. This may require either ditching express-jefferson for `server-koa`, or updating it with koa support.
